"""Downloads the web fonts the screens use into apps/hub-server/static/fonts/.

The hub must be useful with no internet (CLAUDE.md 31). A screen whose stylesheet or
fonts failed to load is not useful -- the data is right and the picture is unreadable --
so nothing the screens need may come from a CDN at run time.

Run this when a face or an icon changes, then commit what it writes:

    cd design && python3 fetch_assets.py

Icons are subsetted by name. The full Material Symbols variable font is megabytes; the
eleven glyphs the screens actually use are a few kilobytes.
"""
import os
import re
import urllib.request

OUT = "../apps/hub-server/static/fonts"
CSS_OUT = "../apps/hub-server/static/fonts.css"

# A browser UA, or Google serves the TrueType fallback instead of woff2.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

FAMILIES = [
    ("bebas-neue",     "family=Bebas+Neue"),
    ("archivo-narrow", "family=Archivo+Narrow:ital,wght@0,400..700;1,400..700"),
    ("jetbrains-mono", "family=JetBrains+Mono:ital,wght@0,100..800;1,100..800"),
]

# Chinese is deliberately NOT downloaded here. Google serves Noto Sans TC as ~105
# unicode-range subsets -- 4 MB and 126 files, most of which no screen will ever ask for.
# The appliance gets it from `fonts-noto-cjk` instead (a dependency of the .deb), macOS has
# PingFang, and the pages name both in their font stack. A CJK face is a system resource,
# not something a web page should carry.

# Every glyph the two screens name. Keep this list in step with the markup; an icon that is
# not here renders as its own name in text, which is at least visibly wrong rather than
# silently blank.
ICONS = "bolt,check_circle,directions_walk,east,flag,groups,hourglass_empty,report,route,sensors,timer"
ICON_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    f"&icon_names={ICONS}&display=block"
)


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request) as response:
        return response.read()


def localise(css, slug):
    """Rewrites each remote woff2 to a file beside this stylesheet, downloading it."""
    seen = {}

    def swap(match):
        remote = match.group(1)
        if remote not in seen:
            name = f"{slug}-{len(seen)}.woff2"
            with open(os.path.join(OUT, name), "wb") as f:
                f.write(fetch(remote))
            seen[remote] = name
            print(f"  {name}")
        return f"url(fonts/{seen[remote]})"

    return re.sub(r"url\((https://fonts\.gstatic\.com[^)]+)\)", swap, css)


def main():
    os.makedirs(OUT, exist_ok=True)
    parts = [
        "/* Generated by design/fetch_assets.py -- do not edit by hand.\n"
        "   Served from the hub, never a CDN: a venue with no internet still has to be able\n"
        "   to read its own screens (CLAUDE.md 31). */\n"
    ]
    for slug, query in FAMILIES:
        print(slug)
        css = fetch(f"https://fonts.googleapis.com/css2?{query}&display=swap").decode()
        parts.append(localise(css, slug))
    print("material-symbols (subset)")
    parts.append(localise(fetch(ICON_URL).decode(), "material-symbols"))

    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    total = sum(os.path.getsize(os.path.join(OUT, n)) for n in os.listdir(OUT))
    print(f"wrote {CSS_OUT} and {len(os.listdir(OUT))} font files ({total // 1024} KB)")


if __name__ == "__main__":
    main()
